import Head from 'next/head'

const About: React.VFC = () => {
  return (
    <>
      <Head>
        <title>A-Programming | オンラインスクール</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      アバウト
    </>
  )
}

export default About
