import Head from 'next/head'
import Footer from '@/components/Footer'
import Lead from '@/components/Lead'
import MainVisual from '@/components/MainVisual'
import Message from '@/components/Message'
import Pagetop from '@/components/Pagetop'
import Price from '@/components/Price'
import QuestionAndAnswer from '@/components/QuestionAndAnswer'
import Sample from '@/components/Sample'
import Works from '@/components/Works'
import styles from '@/styles/Top.module.sass'

const Top: React.VFC = () => {
  return (
    <>
      <Head>
        <title>A-Programming | オンラインスクール</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MainVisual className={styles.main_visual} />
      <Lead className={styles.lead} />
      <Sample className={styles.sample} />
      <Works className={styles.works} />
      <Message className={styles.message} />
      <Price className={styles.price} />
      <QuestionAndAnswer className={styles.q_and_a} />

      <Footer className={styles.footer} />
      <Pagetop disabledElement="#gFooter" />
    </>
  )
}

export default Top
