import Head from 'next/head'
import styles from '@/styles/Top.module.sass'

const Top: React.VFC = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>A-Programming | オンラインスクール</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className={styles.test}>title</h1>
    </>
  )
}

export default Top
